# Generated by Django 2.1 on 2019-07-22 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_auto_20190722_2308'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='data',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hora_fim',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='hora_inicio',
            field=models.TimeField(null=True),
        ),
    ]
