# Generated by Django 2.1 on 2019-07-22 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20190722_2311'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='data',
            new_name='agenda',
        ),
    ]
